CREATE TABLE IF NOT EXISTS generatorreserves_offers_%s
(
generatorreserves_offer_key serial primary key,
Company varchar(4),
Grid_Point varchar(7),
Trading_Date date,
Trading_Period int,
Station varchar(3),
Unit int,
Band1_PLSR_6s_price double precision,
Band1_PLSR_6s_max double precision,
Band1_PLSR_6s_percent double precision,
Band1_PLSR_60s_price double precision,
Band1_PLSR_60s_max double precision,
Band1_PLSR_60s_percent double precision,
Band1_TWDSR_6s_price double precision,
Band1_TWDSR_6s_max double precision,
Band1_TWDSR_60s_price double precision,
Band1_TWDSR_60s_max double precision,
Band2_PLSR_6s_price double precision,
Band2_PLSR_6s_max double precision,
Band2_PLSR_6s_percent double precision,
Band2_PLSR_60s_price double precision,
Band2_PLSR_60s_max double precision,
Band2_PLSR_60s_percent double precision,
Band2_TWDSR_6s_price double precision,
Band2_TWDSR_6s_max double precision,
Band2_TWDSR_60s_price double precision,
Band2_TWDSR_60s_max double precision,
Band3_PLSR_6s_price double precision,
Band3_PLSR_6s_max double precision,
Band3_PLSR_6s_percent double precision,
Band3_PLSR_60s_price double precision,
Band3_PLSR_60s_max double precision,
Band3_PLSR_60s_percent double precision,
Band3_TWDSR_6s_price double precision,
Band3_TWDSR_6s_max double precision,
Band3_TWDSR_60s_price double precision,
Band3_TWDSR_60s_max double precision,
Created_Date date,
Last_Amended_Date date,
UNIQUE(Company,Grid_Point,Trading_Date,Trading_Period,Station,Unit)
);
